/*
    Study
*/
create table st_member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

/*
    Main
*/
create table member
(
    id bigint generated by default as identity,
    memberName varchar(255),
    memberEmail varchar(255),
    memberPhone varchar(12),
    memberPw varchar(255)
        primary key (id)
);

create table board
(
    id bigint generated by default as identity,
    title varchar(255),
    content text,
    member_id bigint,
    hit_cnt bigint,
    reg_date timestamp,
    mod_date timestamp,
    primary key (id)
);

create table board_reply
(
    id bigint generated by default as identity,
    board_Id bigint,
    member_id bigint,
    upper_reply_id bigint,
    reply_level tinyint,
    reply_content text,
    reg_date timestamp,
    mod_date timestamp,
    primary key (id)
);
