/*
    My-sql
*/
-- member 테이블
CREATE TABLE member
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_name VARCHAR(255),
    member_email VARCHAR(255),
    member_phone VARCHAR(12),
    member_pw VARCHAR(255)
);

-- board 테이블
CREATE TABLE board
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    member_id BIGINT,
    view BIGINT,
    reg_date TIMESTAMP,
    mod_date TIMESTAMP
);

-- board_reply 테이블
CREATE TABLE board_reply
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    board_id BIGINT,
    member_id BIGINT,
    upper_reply_id BIGINT,
    reply_level TINYINT,
    reply_content TEXT,
    reg_date TIMESTAMP,
    mod_date TIMESTAMP
);




/*
    H2 DATABASE

create table member
(
    id bigint generated by default as identity,
    memberName varchar(255),
    memberEmail varchar(255),
    memberPhone varchar(12),
    memberPw varchar(255)
        primary key (id)
);

create table board
(
    id bigint generated by default as identity,
    title varchar(255),
    content text,
    member_id bigint,
    hit_cnt bigint,
    reg_date timestamp,
    mod_date timestamp,
    primary key (id)
);

create table board_reply
(
    id bigint generated by default as identity,
    board_Id bigint,
    member_id bigint,
    upper_reply_id bigint,
    reply_level tinyint,
    reply_content text,
    reg_date timestamp,
    mod_date timestamp,
    primary key (id)
);

*/